### ISSUE TITLE
Tracking issue for requirements by DoSW IIT Roorkee

### ISSUE THREAD

**Issue by beingnoble03** [IMGIITRoorkee/omniport-app-bhawan-app#61]
- [ ] Renaming "Address as per Bhawan Records" —> "Student Home Address as per Bhawan Records"
- [ ] Delete/Remove the field "Registration Date" (don't delete "Admission Date")
- [ ] Filter for multiple hostels
- [ ] Bifurcate "Department" and "Degree"
- [ ] Download only works on small student dataset, make it faster and make it work for large student dataset
